steps:
  # 步驟 1: 使用 Docker 建構容器映像
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/python-api:latest"
      - "passwd"

  # 步驟 2: 將映像推送到 Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/python-api:latest"

  # 步驟 3: 部署到 Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "python-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/python-api:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/python-api:latest"
